### PR TITLE
Add missing strings and update translation

### PR DESCRIPTION
**Pull request by Eng2Heb**

### CODE REVIEW

**Comment by rysson** [comment]
I can't verify sentences, but look much more complete :)

**Comment by BankruptEd** [comment]
Is Specto not pretty much finished as an add-on? I have to seen an update in many months, not have I seen any questions and concerns addressed.

**Comment by rysson** [comment]
As I see MrKnow has no time. 
I helped him a little. I can't take over this project because I have not time too. I still have access to git than I can merge patches.

**Comment by BankruptEd** [comment]
Ya, I think he quit. Right around the time the TV Add-ons court case began.
Understandable if that was the reason I suppose.

**Pull request merged**
